config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :calculators, only: [:index, :create]

  root "calculators#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
# frozen_string_literal: true

class Coin < ApplicationRecord
  validates :slug, :price, presence: true
  validates :slug, uniqueness: true

  scope :defaults, -> { where(slug: Constants::Coins::DEFAULTS) }
end

app/models/investment_calculator.rb
# frozen_string_literal: true

class InvestmentCalculator
  include ActiveModel::API
  include ActiveModel::Model
  include ActiveModel::Attributes

  attr_accessor :investment_calculator_results

  attribute :coin, :string
  attribute :amount, :float

  validates :amount, presence: true, numericality: {greater_than: 0}
end

app/models/investment_calculator_result.rb
# frozen_string_literal: true

class InvestmentCalculatorResult
  include ActiveModel::Model
  include ActiveModel::Attributes
  extend ActiveModel::Translation

  attribute :coin, :string
  attribute :number, :integer
  attribute :amount, :float, default: 0
  attribute :crypto_amount, :float, default: 0
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculators_controller.rb
# frozen_string_literal: true

class CalculatorsController < ApplicationController
  before_action :sync_cryptocurrencies_to_coins

  def index
    @current_coins = Coin.defaults
    @investment_calculator = InvestmentCalculator.new
  end

  def create
    result = CalculateInvestment.call(attributes: investment_calculator_params)
    @investment_calculator = result.investment_calculator

    respond_to do |format|
      format.turbo_stream
      format.csv { send_data(export_to_csv, filename: filename) }
      format.json { send_data(export_to_json, filename: filename(format: :json)) }
    end
  end

  private

  def investment_calculator_params
    params.require(:investment_calculator).permit(:amount, :coin)
  end

  def sync_cryptocurrencies_to_coins
    return unless Coin.count.zero?

    SyncCryptocurrenciesToCoins.call
  end

  def filename(format: :csv)
    "data-exported.#{format}"
  end

  def export_to_csv
    CsvExport.new(
      i18n_scope: :investment_calculator_result,
      collection: @investment_calculator.investment_calculator_results
    ).to_csv
  end

  def export_to_json
    @investment_calculator.investment_calculator_results.to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculators_helper.rb
module CalculatorsHelper
end

app/views/calculators/_form.html.erb
<%= form_with model: @investment_calculator, url: calculators_path do |form| %>
  <div class="flex items-start space-x-2">
    <%= render "fields/text", form: form, attribute: :amount %>
    <div>
      <%= form.submit t(:calculate, scope: :generic), class: "rounded-md bg-indigo-600 px-2.5 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
    </div>
  </div>
<% end %>

app/views/calculators/_investment_calculator_result.html.erb
<tr>
  <td class="whitespace-nowrap px-3 py-4 text-sm font-medium text-gray-900 sm:pl-6"><%= investment_calculator_result.number %></td>
  <td class="whitespace-nowrap px-3 py-4 text-sm font-medium text-gray-900 sm:pl-6"><%= number_to_currency investment_calculator_result.amount %></td>
  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= investment_calculator_result.crypto_amount %></td>
</tr>

app/views/calculators/_results.html.erb
<div class="mt-8 flow-root">
  <div class="flex space-x-4 mb-4 justify-end">
    <%= button_to t(:download_csv, scope: :generic), calculators_path(format: :csv), params: { investment_calculator: params[:investment_calculator].to_unsafe_h } %>
    <%= button_to t(:download_json, scope: :generic), calculators_path(format: :json), params: { investment_calculator: params[:investment_calculator].to_unsafe_h } %>
  </div>
  <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="flex space-x-2 inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
      <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
        <%= render "table", results: @investment_calculator.investment_calculator_results.bitcoin, crypto: :bitcoin %>
      </div>
      <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
        <%= render "table", results: @investment_calculator.investment_calculator_results.ethereum, crypto: :ethereum %>
      </div>
    </div>
  </div>
</div>

app/views/calculators/_table.html.erb
<table class="min-w-full divide-y divide-gray-300">
  <thead class="bg-gray-50">
    <tr>
      <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900 sm:pl-6"><%= InvestmentCalculatorResult.human_attribute_name(:number) %></th>
      <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900 sm:pl-6"><%= InvestmentCalculatorResult.human_attribute_name(:amount) %></th>
      <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900 sm:pl-6"><%= InvestmentCalculatorResult.human_attribute_name(:crypto_amount, crypto_name: t(crypto, scope: :cryptos), count: 2) %></th>
    </tr>
  </thead>
  <tbody class="divide-y divide-gray-200 bg-white">
    <%= render partial: "investment_calculator_result", collection: results %>
  </tbody>
</table>

app/views/calculators/create.turbo_stream.erb
<% if @investment_calculator.errors.any? %>
  <%= turbo_stream.update :form do %>
    <%= render "form" %>
  <% end %>
<% else %>
  <%= turbo_stream.update :investment_calculator do %>
    <%= render "results" %>
  <% end %>
<% end %>

app/views/calculators/index.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <div class="flex flex-col space-y-4">
    <div class="flex space-x-4">
      <% @current_coins.each do |coin| %>
        <p><b><%= coin.name %>:</b> <%= number_to_currency coin.price %></p>
      <% end %>
    </div>
    <%= turbo_frame_tag :form do %>
      <%= render "form" %>
    <% end %>
  </div>
  <%= turbo_frame_tag :investment_calculator %>
</div>

app/views/fields/_text.html.erb
<%- error = form.object.errors[attribute].first %>
<% error_class = "border border-red-500" if error.present? %>
<div>
  <div class="relative rounded-md shadow-sm <%= error_class %>">
    <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
      <span class="text-gray-500 sm:text-sm">$</span>
    </div>
    <%= form.text_field attribute, placeholder: "0.00", class: "block w-full rounded-md border-0 py-1.5 pl-7 pr-12 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6", "aria-describedby": "price-currency" %>
    <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center pr-3">
      <span class="text-gray-500 sm:text-sm" id="price-currency">USD</span>
    </div>
  </div>
  <%= content_tag :p, error, class: "help-error text-red-500 text-sm" if error.present? %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoInvestment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>